### ISSUE TITLE
restriktor has been archived from CRAN

### ISSUE THREAD

**Issue by pkoaz** [LeonardV/restriktor#15]
The package has been archived from CRAN due to the norm2 package being archived.  tried to install an older version of norm2 from source but ran into fortran problems. Is there a way to work around this dependency?

https://cran.r-project.org/package=restriktor

```
Package ‘restriktor’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/restriktor).

Archived on 2023-08-25 as requires archived package 'norm2'.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-08-25_check_results_restriktor.html).

Please use the canonical form https://cran.r-project.org/package=restriktor to link to this page.
```

**Comment by LeonardV** [comment]
Dear Peter,

I hope this message finds you well. I wanted to inform you that I have
successfully replaced the 'norm2' package with the updated 'norm' package
in our project. As a result, all functionalities should now be operating
smoothly.

Additionally, I would like to bring to your attention that on September
14th, I resubmitted version 0.5-30 of the Restriktor package. However, it
appears to be treated as a new submission rather than an update to the
existing version and it is still pending for manual inspection.

If there are any specific steps that need to be taken to ensure that this
resubmission is recognized as an update, please let me know.

Best,
Leonard

Op di 12 sep 2023 om 09:02 schreef Peter Konings ***@***.***>:

**Comment by LeonardV** [comment]
The package norm2 has been replaced by the norm package. Unfortunately, restriktor is still not on CRAN. You can install it directly from github (for now)

**Comment by LeonardV** [comment]
Restriktor is back on CRAN
